import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Project } from '../types';
import { formatRupiah, getStats } from './helpers';

// Extend jsPDF to include autoTable type
interface jsPDFCustom extends jsPDF {
    lastAutoTable: { finalY: number };
}

// ==========================================
// HELPER FUNCTIONS
// ==========================================

const formatDateID = (dateStr: string): string => {
    return new Date(dateStr).toLocaleDateString('id-ID', {
        day: 'numeric',
        month: 'long',
        year: 'numeric'
    });
};

const formatMonthYear = (month: number, year: number): string => {
    const date = new Date(year, month, 1);
    return date.toLocaleDateString('id-ID', { month: 'long', year: 'numeric' });
};

const addHeader = (doc: jsPDFCustom, title: string, subtitle: string, pageWidth: number, _margin: number): number => {
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(title, pageWidth / 2, 20, { align: "center" });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, pageWidth / 2, 28, { align: "center" });

    return 35;
};

const addFooter = (doc: jsPDFCustom) => {
    const totalPages = doc.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.width;

    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
            `Generated by Guna Karya - ${new Date().toLocaleString('id-ID')} | Halaman ${i} dari ${totalPages}`,
            pageWidth / 2,
            doc.internal.pageSize.height - 10,
            { align: 'center' }
        );
    }
    doc.setTextColor(0);
};

// ==========================================
// 1. MONTHLY FINANCE REPORT
// ==========================================

export const generateMonthlyFinanceReport = (
    project: Project,
    month: number, // 0-11
    year: number
) => {
    const doc = new jsPDF() as jsPDFCustom;
    const pageWidth = doc.internal.pageSize.width;
    const margin = 15;

    // Filter transactions for selected month
    const monthTransactions = (project.transactions || []).filter(t => {
        const d = new Date(t.date);
        return d.getMonth() === month && d.getFullYear() === year;
    });

    const income = monthTransactions.filter(t => t.type === 'income');
    const expense = monthTransactions.filter(t => t.type === 'expense');
    const totalIncome = income.reduce((sum, t) => sum + t.amount, 0);
    const totalExpense = expense.reduce((sum, t) => sum + t.amount, 0);

    // HEADER
    let finalY = addHeader(
        doc,
        "LAPORAN KEUANGAN BULANAN",
        `${project.name} - ${formatMonthYear(month, year)}`,
        pageWidth,
        margin
    );

    // PROJECT INFO BOX
    doc.setFillColor(248, 250, 252);
    doc.rect(margin, finalY, pageWidth - (margin * 2), 20, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.rect(margin, finalY, pageWidth - (margin * 2), 20, 'S');

    doc.setFontSize(9);
    doc.text(`Klien: ${project.client}`, margin + 5, finalY + 7);
    doc.text(`Lokasi: ${project.location || '-'}`, margin + 5, finalY + 13);
    doc.text(`Periode: ${formatMonthYear(month, year)}`, pageWidth - margin - 5, finalY + 7, { align: 'right' });
    doc.text(`Tanggal Cetak: ${formatDateID(new Date().toISOString())}`, pageWidth - margin - 5, finalY + 13, { align: 'right' });

    finalY += 30;

    // RINGKASAN KEUANGAN
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("RINGKASAN", margin, finalY);
    finalY += 8;

    // Summary boxes
    const boxWidth = (pageWidth - (margin * 2) - 20) / 3;

    // Income Box
    doc.setFillColor(220, 252, 231);
    doc.rect(margin, finalY, boxWidth, 25, 'F');
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Total Pemasukan", margin + 5, finalY + 8);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(22, 163, 74);
    doc.text(formatRupiah(totalIncome), margin + 5, finalY + 18);
    doc.setTextColor(0);

    // Expense Box
    doc.setFillColor(254, 226, 226);
    doc.rect(margin + boxWidth + 10, finalY, boxWidth, 25, 'F');
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Total Pengeluaran", margin + boxWidth + 15, finalY + 8);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(220, 38, 38);
    doc.text(formatRupiah(totalExpense), margin + boxWidth + 15, finalY + 18);
    doc.setTextColor(0);

    // Balance Box
    const balance = totalIncome - totalExpense;
    if (balance >= 0) {
        doc.setFillColor(219, 234, 254);
    } else {
        doc.setFillColor(254, 249, 195);
    }
    doc.rect(margin + (boxWidth * 2) + 20, finalY, boxWidth, 25, 'F');
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Sisa Kas", margin + (boxWidth * 2) + 25, finalY + 8);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    if (balance >= 0) {
        doc.setTextColor(37, 99, 235);
    } else {
        doc.setTextColor(202, 138, 4);
    }
    doc.text(formatRupiah(balance), margin + (boxWidth * 2) + 25, finalY + 18);
    doc.setTextColor(0);

    finalY += 35;

    // DETAIL PEMASUKAN
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("DETAIL PEMASUKAN", margin, finalY);
    finalY += 3;

    if (income.length > 0) {
        // Group by category
        const incomeByCategory: { [key: string]: number } = {};
        income.forEach(t => {
            incomeByCategory[t.category] = (incomeByCategory[t.category] || 0) + t.amount;
        });

        const incomeData = Object.entries(incomeByCategory).map(([cat, amt]) => [
            cat,
            `${income.filter(t => t.category === cat).length} transaksi`,
            formatRupiah(amt)
        ]);
        incomeData.push(['TOTAL', '', formatRupiah(totalIncome)]);

        autoTable(doc, {
            startY: finalY + 2,
            head: [['Kategori', 'Jumlah Transaksi', 'Nominal']],
            body: incomeData,
            theme: 'striped',
            headStyles: { fillColor: [22, 163, 74] },
            styles: { fontSize: 9, cellPadding: 3 },
            margin: { left: margin, right: margin }
        });

        finalY = doc.lastAutoTable.finalY + 10;
    } else {
        doc.setFontSize(9);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(100);
        doc.text("Tidak ada pemasukan pada bulan ini.", margin, finalY + 6);
        doc.setTextColor(0);
        finalY += 15;
    }

    // DETAIL PENGELUARAN
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("DETAIL PENGELUARAN", margin, finalY);
    finalY += 3;

    if (expense.length > 0) {
        // Group by category
        const expenseByCategory: { [key: string]: number } = {};
        expense.forEach(t => {
            expenseByCategory[t.category] = (expenseByCategory[t.category] || 0) + t.amount;
        });

        const expenseData = Object.entries(expenseByCategory).map(([cat, amt]) => [
            cat,
            `${expense.filter(t => t.category === cat).length} transaksi`,
            formatRupiah(amt)
        ]);
        expenseData.push(['TOTAL', '', formatRupiah(totalExpense)]);

        autoTable(doc, {
            startY: finalY + 2,
            head: [['Kategori', 'Jumlah Transaksi', 'Nominal']],
            body: expenseData,
            theme: 'striped',
            headStyles: { fillColor: [220, 38, 38] },
            styles: { fontSize: 9, cellPadding: 3 },
            margin: { left: margin, right: margin }
        });

        finalY = doc.lastAutoTable.finalY + 10;
    } else {
        doc.setFontSize(9);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(100);
        doc.text("Tidak ada pengeluaran pada bulan ini.", margin, finalY + 6);
        doc.setTextColor(0);
        finalY += 15;
    }

    // DAFTAR TRANSAKSI (if space allows)
    if (finalY < 200 && monthTransactions.length > 0 && monthTransactions.length <= 20) {
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text("RINCIAN TRANSAKSI", margin, finalY);
        finalY += 3;

        const txData = monthTransactions
            .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
            .map(t => [
                formatDateID(t.date),
                t.type === 'income' ? 'Masuk' : 'Keluar',
                t.category,
                t.description || '-',
                formatRupiah(t.amount)
            ]);

        autoTable(doc, {
            startY: finalY + 2,
            head: [['Tanggal', 'Tipe', 'Kategori', 'Keterangan', 'Nominal']],
            body: txData,
            theme: 'grid',
            headStyles: { fillColor: [51, 65, 85] },
            styles: { fontSize: 8, cellPadding: 2 },
            columnStyles: {
                3: { cellWidth: 50 }
            },
            margin: { left: margin, right: margin }
        });
    }

    // FOOTER
    addFooter(doc);

    // Save
    doc.save(`Laporan_Keuangan_${project.name.replace(/\s+/g, '_')}_${formatMonthYear(month, year).replace(/\s+/g, '_')}.pdf`);
};

// ==========================================
// 2. PAYROLL REPORT
// ==========================================

export const generatePayrollReport = (
    project: Project,
    startDate: string,
    endDate: string
) => {
    const doc = new jsPDF() as jsPDFCustom;
    const pageWidth = doc.internal.pageSize.width;
    const margin = 15;

    // Filter attendance logs for date range
    const filteredLogs = (project.attendanceLogs || []).filter(log => {
        const logDate = new Date(log.date).getTime();
        return logDate >= new Date(startDate).getTime() && logDate <= new Date(endDate).getTime();
    });

    // HEADER
    let finalY = addHeader(
        doc,
        "REKAP GAJI PEKERJA",
        `${project.name}`,
        pageWidth,
        margin
    );

    // INFO BOX
    doc.setFillColor(248, 250, 252);
    doc.rect(margin, finalY, pageWidth - (margin * 2), 15, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.rect(margin, finalY, pageWidth - (margin * 2), 15, 'S');

    doc.setFontSize(9);
    doc.text(`Periode: ${formatDateID(startDate)} - ${formatDateID(endDate)}`, margin + 5, finalY + 10);
    doc.text(`Tanggal Cetak: ${formatDateID(new Date().toISOString())}`, pageWidth - margin - 5, finalY + 10, { align: 'right' });

    finalY += 25;

    // WORKER TABLE
    const workers = project.workers || [];

    if (workers.length === 0) {
        doc.setFontSize(11);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(100);
        doc.text("Belum ada data pekerja.", margin, finalY);
        doc.setTextColor(0);
    } else {
        // Calculate attendance for each worker in date range
        const workerData = workers.map(worker => {
            const workerLogs = filteredLogs.filter(l => l.workerId === worker.id);

            let days = 0;
            workerLogs.forEach(log => {
                if (log.status === 'Hadir') days += 1;
                else if (log.status === 'Setengah') days += 0.5;
                else if (log.status === 'Lembur') days += 1.5;
            });

            let dailyRate = worker.mandorRate;
            if (worker.wageUnit === 'Mingguan') dailyRate = worker.mandorRate / 7;
            if (worker.wageUnit === 'Bulanan') dailyRate = worker.mandorRate / 30;

            const totalDue = days * dailyRate;

            // Calculate paid amount in date range
            const paidInRange = (project.transactions || [])
                .filter(t =>
                    t.workerId === worker.id &&
                    t.type === 'expense' &&
                    t.category === 'Upah' &&
                    new Date(t.date).getTime() >= new Date(startDate).getTime() &&
                    new Date(t.date).getTime() <= new Date(endDate).getTime()
                )
                .reduce((sum, t) => sum + t.amount, 0);

            return [
                worker.name,
                worker.role,
                formatRupiah(dailyRate),
                days.toString(),
                formatRupiah(totalDue),
                formatRupiah(paidInRange),
                formatRupiah(totalDue - paidInRange)
            ];
        });

        // Calculate totals
        const totalDue = workerData.reduce((sum, row) => {
            const val = parseInt(row[4].replace(/[^\d]/g, '')) || 0;
            return sum + val;
        }, 0);
        const totalPaid = workerData.reduce((sum, row) => {
            const val = parseInt(row[5].replace(/[^\d]/g, '')) || 0;
            return sum + val;
        }, 0);
        const totalBalance = workerData.reduce((sum, row) => {
            const val = parseInt(row[6].replace(/[^\d]/g, '')) || 0;
            return sum + val;
        }, 0);

        workerData.push([
            'TOTAL',
            '',
            '',
            '',
            formatRupiah(totalDue),
            formatRupiah(totalPaid),
            formatRupiah(totalBalance)
        ]);

        autoTable(doc, {
            startY: finalY,
            head: [['Nama', 'Posisi', 'Rate/Hari', 'Hari Kerja', 'Total Hak', 'Sudah Dibayar', 'Sisa']],
            body: workerData,
            theme: 'striped',
            headStyles: { fillColor: [51, 65, 85] },
            styles: { fontSize: 8, cellPadding: 2 },
            columnStyles: {
                2: { halign: 'right' },
                3: { halign: 'center' },
                4: { halign: 'right' },
                5: { halign: 'right' },
                6: { halign: 'right' }
            },
            margin: { left: margin, right: margin }
        });

        finalY = doc.lastAutoTable.finalY + 15;
    }

    // ATTENDANCE DETAIL (if space allows)
    if (finalY < 180 && filteredLogs.length > 0 && filteredLogs.length <= 50) {
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text("DETAIL ABSENSI", margin, finalY);
        finalY += 5;

        // Group by date
        const logsByDate: { [date: string]: typeof filteredLogs } = {};
        filteredLogs.forEach(log => {
            if (!logsByDate[log.date]) logsByDate[log.date] = [];
            logsByDate[log.date].push(log);
        });

        const detailData: string[][] = [];
        Object.entries(logsByDate)
            .sort(([a], [b]) => new Date(a).getTime() - new Date(b).getTime())
            .forEach(([date, logs]) => {
                logs.forEach((log, idx) => {
                    const worker = workers.find(w => w.id === log.workerId);
                    detailData.push([
                        idx === 0 ? formatDateID(date) : '',
                        worker?.name || '-',
                        log.status,
                        log.note || '-'
                    ]);
                });
            });

        autoTable(doc, {
            startY: finalY,
            head: [['Tanggal', 'Nama', 'Status', 'Catatan']],
            body: detailData,
            theme: 'grid',
            headStyles: { fillColor: [71, 85, 105] },
            styles: { fontSize: 8, cellPadding: 2 },
            margin: { left: margin, right: margin }
        });
    }

    // FOOTER
    addFooter(doc);

    // Save
    const fileName = `Rekap_Gaji_${project.name.replace(/\s+/g, '_')}_${startDate}_${endDate}.pdf`;
    doc.save(fileName);
};

// ==========================================
// 3. PROGRESS REPORT (FOR CLIENTS)
// ==========================================

export const generateProgressReport = (project: Project) => {
    const doc = new jsPDF() as jsPDFCustom;
    const pageWidth = doc.internal.pageSize.width;
    const margin = 15;

    const stats = getStats(project);

    // HEADER
    let finalY = addHeader(
        doc,
        "LAPORAN PROGRESS PROYEK",
        project.name,
        pageWidth,
        margin
    );

    // PROJECT INFO BOX
    doc.setFillColor(248, 250, 252);
    doc.rect(margin, finalY, pageWidth - (margin * 2), 25, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.rect(margin, finalY, pageWidth - (margin * 2), 25, 'S');

    doc.setFontSize(9);
    doc.text(`Klien: ${project.client}`, margin + 5, finalY + 8);
    doc.text(`Lokasi: ${project.location || '-'}`, margin + 5, finalY + 14);
    doc.text(`Status: ${project.status}`, margin + 5, finalY + 20);

    doc.text(`Mulai: ${formatDateID(project.startDate)}`, pageWidth - margin - 5, finalY + 8, { align: 'right' });
    doc.text(`Target: ${formatDateID(project.endDate)}`, pageWidth - margin - 5, finalY + 14, { align: 'right' });
    doc.text(`Tanggal Cetak: ${formatDateID(new Date().toISOString())}`, pageWidth - margin - 5, finalY + 20, { align: 'right' });

    finalY += 35;

    // PROGRESS SUMMARY
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("RINGKASAN PROGRESS", margin, finalY);
    finalY += 10;

    // Progress bar visual
    const barWidth = pageWidth - (margin * 2);
    const barHeight = 20;

    // Background
    doc.setFillColor(226, 232, 240);
    doc.rect(margin, finalY, barWidth, barHeight, 'F');

    // Progress fill
    const progressWidth = (stats.prog / 100) * barWidth;
    doc.setFillColor(34, 197, 94);
    doc.rect(margin, finalY, progressWidth, barHeight, 'F');

    // Progress text
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(`${stats.prog.toFixed(1)}%`, margin + progressWidth / 2, finalY + 13, { align: 'center' });
    doc.setTextColor(0);

    finalY += barHeight + 15;

    // RAB PROGRESS TABLE
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("PROGRESS PER ITEM PEKERJAAN", margin, finalY);
    finalY += 5;

    const rabItems = project.rabItems || [];
    if (rabItems.length > 0) {
        // Track previous category to avoid repetition
        let prevCategory = '';
        const rabData = rabItems.map(item => {
            const showCategory = item.category !== prevCategory;
            prevCategory = item.category;
            return [
                showCategory ? item.category : '',
                item.name,
                `${item.progress}%`
            ];
        });

        autoTable(doc, {
            startY: finalY,
            head: [['Kategori', 'Pekerjaan', 'Progress']],
            body: rabData,
            theme: 'striped',
            headStyles: { fillColor: [51, 65, 85] },
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                2: { halign: 'center', cellWidth: 25 }
            },
            margin: { left: margin, right: margin },
            didParseCell: function (data) {
                if (data.section === 'body' && data.column.index === 2) {
                    const progress = parseInt(data.cell.text[0]) || 0;
                    if (progress === 100) {
                        data.cell.styles.textColor = [22, 163, 74];
                        data.cell.styles.fontStyle = 'bold';
                    } else if (progress >= 50) {
                        data.cell.styles.textColor = [37, 99, 235];
                    } else if (progress > 0) {
                        data.cell.styles.textColor = [234, 179, 8];
                    }
                }
            }
        });

        finalY = doc.lastAutoTable.finalY + 15;
    }

    // RECENT PHOTOS (if space allows)
    const recentPhotos = (project.gallery || [])
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
        .slice(0, 5);

    if (recentPhotos.length > 0 && finalY < 230) {
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text("DOKUMENTASI TERBARU", margin, finalY);
        finalY += 8;

        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");

        recentPhotos.forEach((photo, index) => {
            doc.setTextColor(37, 99, 235);
            const caption = photo.caption ? ` - ${photo.caption}` : '';
            const progressStr = photo.progress ? ` (Progress: ${photo.progress.toFixed(0)}%)` : '';
            doc.text(`[Foto ${index + 1}] ${formatDateID(photo.date)}${caption}${progressStr}`, margin, finalY);
            doc.link(margin, finalY - 3, 100, 5, { url: photo.url });
            finalY += 6;
        });

        doc.setTextColor(0);
        doc.setFontSize(8);
        doc.setFont("helvetica", "italic");
        doc.text("* Klik link di atas untuk melihat foto.", margin, finalY + 3);
    }

    // FOOTER
    addFooter(doc);

    // Save
    doc.save(`Laporan_Progress_${project.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// ==========================================
// HELPER: Get available months for a project
// ==========================================

export const getAvailableMonths = (project: Project): { month: number; year: number; label: string }[] => {
    const transactions = project.transactions || [];
    const monthsSet = new Set<string>();

    transactions.forEach(t => {
        const d = new Date(t.date);
        monthsSet.add(`${d.getFullYear()}-${d.getMonth()}`);
    });

    // Also include current month
    const now = new Date();
    monthsSet.add(`${now.getFullYear()}-${now.getMonth()}`);

    return Array.from(monthsSet)
        .map(key => {
            const [year, month] = key.split('-').map(Number);
            return {
                month,
                year,
                label: formatMonthYear(month, year)
            };
        })
        .sort((a, b) => (b.year - a.year) || (b.month - a.month));
};
